#!/bin/bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
# All the codes are uploaded in the repository. This script will run a dummy test script which explains the purposes of the other codes.

python3 test_script.py -t nluma # can change this to luma or nluma